### ISSUE TITLE
[ExpertView] layout

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#10]
- status bar switch
- 50% column layout 
- expert view slides in from the right, use transition time and function consistent with the rest of the application
- full screen
- tabs (again)
- when expert view takes 50% width - reflow the main layout (tabs and components have different paddings etc [see here](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=395%3A17981))

additional points:
resizable: no

**Comment by tarnas14** [comment]
a lot of this was done before while working on layout, so this is done together with #45

**Comment by corquaid** [comment]
Reviewed and closed.
