### ISSUE TITLE
main layout viewport too wide on expert view

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#100]
Main layout takes too much space when expert view is open (it is more than 50% of viewport)

This makes centered layouts broken:
![2022-04-27-112044_1920x1080_scrot](https://user-images.githubusercontent.com/9142942/165487050-ecd972e8-670d-46aa-bc6b-9db91166cc85.png)

expected:
centered layouts work visually correct when expert view is open

**Comment by corquaid** [comment]
Reviewed and closed.
