### ISSUE TITLE
Research copy+paste functionality on macOS w/Tauri

### ISSUE THREAD

**Issue by corquaid** [Altalogy/tari#110]
MOVING TO BACKLOG: adjustments required for final version, initial setup complete.

- Keyboard commands for Copy / Paste / Select All appear not to work on macOS inside the Tauri app.
- Found this GitHub issue:
[https://github.com/tauri-apps/tauri/issues/2397](url)
- Suggests that we need to create Menus / Submenus within `src-tauri/src/main.rs` to activate the keyboard shortcuts.

**Comment by corquaid** [comment]
Reviewed & closed.

**Comment by tarnas14** [comment]
check if you can have copy/paste without the app bar

make sure that we need appbar

**Comment by tomaszantas** [comment]
Confirmed, cmd+C / cmd + V (copy / paste) keyboard shortcuts doesn't work on mac without the menu bar.
