### ISSUE TITLE
Add 'Copied!' feedback to <CopyBox />

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#124]
Right now an ugly alert is shown when user clicks "copy" icon in CopyBox

Add a tooltip "Copied to clipboard!" that appears above "copy" icon.

The tooltip could be a <Tag variant='info'/>
It should disappear automatically after 1~2s
Possibly fade away transparency instead of just hiding the tooltip

**Comment by corquaid** [comment]
Reviewed and closed.
