### ISSUE TITLE
[T-Bot] T-Bot animation

### ISSUE THREAD

**Issue by corquaid** [Altalogy/tari#139]
Extracted from #21.

"there should be a way to show the bot with animation:
_minimal implementation_: expand the bot from 0x0 to target dimensions, probably with bezier
_nice to have_: expand the bot body first, then animate his face and eyes in (this could be extracted to a separate issue to be pushed back, if proves to be time consuming)"

**Comment by tomaszantas** [comment]
Nice to have animation moved to the #255
