### ISSUE TITLE
Handle errors for Containers Expert View

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#143]
when communicating with backend to start/stop dockers, show errors if the action throws an error

we agreed to show feedback in situations like these by warning modal
[figma link](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=603%3A72005)

**Comment by corquaid** [comment]
Reviewed and closed.
