### ISSUE TITLE
[Primitive] Input - password strength meter

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#144]
[https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=397%3A13339](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=397%3A13339)

**Comment by corquaid** [comment]
Follow-up issue #217 created to fix colour band display.

Closing this previous issues.
