### ISSUE TITLE
[Random] Generate random password automatically

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#145]
[https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=397%3A13339](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=397%3A13339)

**Comment by tomaszantas** [comment]
It has been decided to remove this feature.

**Comment by corquaid** [comment]
Reviewed and closed.
