### ISSUE TITLE
[Backend] Stream mining and wallet events to front-end

### ISSUE THREAD

**Issue by CjS77** [Altalogy/tari#155]
Provide a new Tauri event stream that provides the following events.

- transaction received
- transaction sent
- transaction cancelled
- transaction mined but unconfirmed
- transaction mined and confirmed
- New block mined

**Comment by alex1307** [comment]
All events above are streamed to the launchpad front-end. Should be closed.

**Comment by tarnas14** [comment]
implemented in two PRs:
#238
#246
