### ISSUE TITLE
[Wallet] Main functionality

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#16]
- add password (unlock your wallet, if not unlocked)
- password should not be remembered between sessions
- Tari Wallet box (with "running" indicator)
- show Tari Wallet ID as emojis
- Balance box (WITHOUT "send funds", just the info)
- use a balance chart *icon* for on the balance box

to discuss with @tari
- command for getting wallet info (`{ running: boolean; walletId: string; balance: number; availableBalance: number; }`) - we can add an endpoint to backend, let's assume it for now
- event about changes of wallet.running state - can be taken from `'tari://docker-system-event'`

**Comment by tarnas14** [comment]
for next PRs:
- [x] properly styled password input - after #96 
- [x] wallet address (with emoji) - question @ tari, waiting for pointers - #107

**Comment by tarnas14** [comment]
from #107 
- [x] After submitting the password, the input goes blank for a 2 seconds.
- [x] wallet id doesn't fit the input (line break) - setting fontSize to 14px should help
- [x] (Already mentioned in comments) - toggling the smiley makes icons going up and down by 1px

**Comment by tomaszantas** [comment]
Review:

1. Few minor fixes was done in this PR: #128 
2. Style of the button need to be improved with this #75 

All looks good, including checkboxes from previous comments.
