### ISSUE TITLE
expert view "stop" buttons are in the wrong color

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#172]
![image](https://user-images.githubusercontent.com/9142942/168757221-4b12c163-6aca-49cb-8ed2-0f034c49474e.png)

^ wrong

make it like in the figma:

![image](https://user-images.githubusercontent.com/9142942/168757583-0a17daa4-bb3e-459b-9e35-39e26de32b00.png)

**Comment by corquaid** [comment]
Reviewed and closed.
