### ISSUE TITLE
Remove 'unhealthy' information outside of expert view

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#173]
remove the 'unhealthy' state from service:
![image](https://user-images.githubusercontent.com/9142942/168752684-573f9f62-3e49-4289-945e-b5a05443d981.png)

Acceptance criteria:
- if not all containers are running, the service should be shown as 'stopped'
- when user clicks 'start', the application should run missing containers

Reasoning:
regular user might not know or be interested in the containers side of things
for them we should consider the service either running (all necessary containers are running) or not running at all

**Comment by tarnas14** [comment]
@CjS77 
we had a discussion with the UI/UX team and they said we should not overload the "regular" user with information
it should be enough to start/stop for them and the system is going to take care of it under the hood
but if you go into expert view you can see with greater resolution which container is running and which isn't etc

**Comment by CjS77** [comment]
I agree with the KISS approach.

**Comment by corquaid** [comment]
Reviewed and closed.
