### ISSUE TITLE
[Mining] Get event about mined Tari / Monero in Tari and Merged mining

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#188]
- [ ] ensure that containers setup is correct and containers do _real_ mining
- [ ] receive and process the event

It is blocked by two:

- need to use valid wallet
- #238

**Comment by tarnas14** [comment]
I think 'preserve the history of sessions' should be done in #46 
we don't need the history to mine, the history is remembered only for the purpose of showing the statistics

**Comment by tarnas14** [comment]
waiting for "is_coinbase" to be populated correctly for transactions #358

**Comment by tarnas14** [comment]
as above (#358 will deal with the aftermath of this task)
