### ISSUE TITLE
[Wallet] help prompts

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#20]
1. main help above and below wallet boxes
2. account balance difference from available balance

### 1. :
**Tari wallet is a hardware app that allows you to manage your Tari balance.**
_Only way to unlock access to your Tari wallet is by providing correct Tari wallet Password. Remember, unlike your social media account or bank account passwords your Tari wallet password can never be recovered._
![image](https://user-images.githubusercontent.com/9142942/174803858-e4df740d-5167-49d7-b872-2234df97511a.png)
![image](https://user-images.githubusercontent.com/9142942/174803887-1f7e6bbf-5c25-410b-a8c3-2d58748c4c79.png)

### 2. :
https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=446%3A334091

**Comment by corquaid** [comment]
Reviewed and closed.
