### ISSUE TITLE
[T-Bot] dumb component to show different states

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#21]
- create the T-Bot (html, svg) - to include him in different Components easily
- color for Tari, color for Monero
- have interface for heart eyes
- loading eyes
- radar instead of eyes
- big radius shadow (see mining notification on [figma](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=686%3A77194))
- there should be a way to show the bot with animation:
_minimal implementation_: expand the bot from 0x0 to target dimensions, probably with bezier
_nice to have_: expand the bot body first, then animate his face and eyes in (this could be extracted to a separate issue to be pushed back, if proves to be time consuming)

**Comment by corquaid** [comment]
I've extracted the animation portion of this into a separate issue #139.

**Comment by tomaszantas** [comment]
SVG animations moved to #255
