### ISSUE TITLE
Manage logs containers in launchpad

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#269]
AC:
- [ ] ~add info about default password? (admin:admin) <- ask the UX team to do it~ moved to #293
- [x] reimplement environment showcased in #264 as something that can be called from launchpad
- [x] add promtail/loki/grafana containers to the list of containers so the application can listen for events and show performance etc

**Comment by CjS77** [comment]
> add info about default password? (admin:admin) <- ask the UX team to do it

Can we make this a separate issue? I'm not sure how we do this exactly

> reimplement environment showcased in https://github.com/Altalogy/tari/pull/264 as something that can be called from launchpad

Done, but might FE code might be a bit hacky. Maybe tidy up in a follow up PR if required

> add promtail/loki/grafana containers to the list of containers so the application can listen for events and show performance etc

ditto
