### ISSUE TITLE
TBot help prompt crashes the application

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#307]
(blocked by #305)

![tbotprompt-bug](https://user-images.githubusercontent.com/9142942/174996962-c314b364-beb7-4cfe-a60d-03010e968a34.gif)

steps to reproduce:
1. open a TBot help prompt with number of messages > 1, then close it
2. open a TBot help prompt with less messages than the previous one

current result:
app crashes

expected result:
TBot prompt is rendered correctly

**Comment by tarnas14** [comment]
possibly resolved by #306

**Comment by corquaid** [comment]
Reviewed and closed.
