### ISSUE TITLE
[BaseNode] Check if base node is already synced

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#385]
Base Node sync in Onboarding:

- [x] Check if Base node is already synced
- [ ] Wait for the base node: Backend gets an error (grpc related - base node is not running yet) when we invoke listener right after starting the service. For now, frontend waits 10sec before invoking base node progress stream

**Comment by CjS77** [comment]
For the 2nd issue, I suggest retrying from the front-end periodically until the gRPC service is ready

**Comment by tomaszantas** [comment]
**2nd issue:**

If the app doesn't wait ie. 10 sec, this is reported in the console:

```
ERROR tari_launchpad::base_node_grpc] Failed reading progress from base node: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
```

@alex1307  @CjS77 
Is there a way to return this exception in the response to the `invoke('base_node_sync_progress')`? So then we can  retry until it works
