### ISSUE TITLE
Add Build job to CircleCI

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#59]
Add building Tauri with CircleCI.

- [ ] discuss this idea with Tari. Maybe they would have some suggestions on this.

Use native platform in CircleCI job (ie. MacOS, Windows, Linux) that install all dependencies (Rust, Node, etc.), and store builds as artifacts, so it can be easily downloaded and tested on different platforms.

- [ ] use dedicated branch to trigger builds on CircleCI (running jobs on CircleCI for native platforms costs more credits than Docker on Linux).

**Comment by tarnas14** [comment]
we're close to merging to upstream, will deal with it there
