### ISSUE TITLE
Start tari dockers through backend

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#61]
from #12 

figure out how to start mining from the app

**Comment by tarnas14** [comment]
# putting on hold

branch `launchpad/chore/update_launchpad_v2_docker_rig`

I'm still doing something wrong with base_node building
```bash
Command: tari_base_node -c /var/tari/config/config.toml -b /var/tari/base_node --non-interactive-mode
Initializing logging according to "/var/tari/base_node/config/base_node/log4rs.yml"
ExitError { exit_code: ConfigError, details: Some("Invalid value for `common`: unknown field `dibbler`, expected `override_from` or `base_path`") }
12:21 ERROR Exiting with code (101): ExitError { exit_code: ConfigError, details: Some("Invalid value for `common`: unknown field `dibbler`, expected `override_from` or `base_path`") }
```

I'm building the images with `build_images.sh` in the applications/launchpad (copied to our directory launchpad_v2)
I updated all the docer_rig Dockerfiles to use launchpad_v2

I also added `COPY config /var/tari/config` (after copying config.toml from `applications/launchpad_v2/src-tauri/assets`)
to base_node.Dockerfile because I looked into the container and it is starting basenode with `-c /var/tari/config/config.toml`
but it wasn't anywhere on the container
_however_, that didn't help at all, still the same error of incorrect config fields

what's worse, I don't even know where base_node is getting its config, there's no config.toml in /var/tari/base_node that it could fallback to

**Comment by tarnas14** [comment]
questions:
1. on startup - can we list dockers and get info which ones are running to initialize app state?

**Comment by corquaid** [comment]
Reviewed and closed.
