### ISSUE TITLE
[Primitive] Tag component

### ISSUE THREAD

**Issue by corquaid** [Altalogy/tari#81]
Tag / label UI component

<img width="550" alt="image" src="https://user-images.githubusercontent.com/69508715/164234358-4a97fbb3-07c6-4706-8b81-aacb0ca71589.png">

**Comment by tomaszantas** [comment]
Review:

- [x] Large tag has `30px` height, should be `26px` ( #104 )

**Comment by corquaid** [comment]
Reviewed; ready to close.
